site_name: Genes & Health TRE Documentation
site_url: https://genes-and-health.github.io/TRE-docs
repo_url: https://github.com/genes-and-health/TRE-docs
edit_uri: edit/main/docs/
theme:
  name: material
  logo: images/branding/genes-and-health-logo-green.svg
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.action.edit
    - navigation.footer
    # - navigation.sections   # show section headers in the left nav
    # - navigation.indexes    # make section index pages clickable
    - navigation.path
    # Optional behaviors:
    # - navigation.expand   # expand all sections by default (user can still collapse)
    # - toc.integrate       # puts the current pageâ€™s headings under it in the left nav  
    - navigation.instant       # Updates nav highlighting as you scroll
    - navigation.tracking      # Tracks current section in sidebar
  palette: 
  # Palette toggle for light mode
  - scheme: default
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode

  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - js/edit-link-newtab.js
markdown_extensions:
  - admonition
  - def_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - md_in_html
nav:
  - Latest TRE data updates and changes: latest-tre-data-updates-and-changes.md
  - Getting started as a new user:
      - What is a TRE?: getting-started-as-a-new-user/what-is-a-tre.md
      - Getting access and setting up a profile: getting-started-as-a-new-user/steps-to-get-access.md
      - Sandboxes and what each sandbox can access: sandboxes-and-what-each-sandbox-can-access.md
      - Starting the TRE: getting-started-as-a-new-user/starting-the-tre.md
      - Shutting down the TRE: getting-started-as-a-new-user/shutting-down-the-tre.md
      - Choosing your required virtual machine configuration: getting-started-as-a-new-user/choosing-your-virtual-machine.md
      - How to increase your disk size: getting-started-as-a-new-user/how-to-increase-your-disk-size.md
  - Using the TRE:
      - Understanding TRE folders and buckets: using-the-tre/understanding-tre-folders-and-buckets.md
      - Handling files and folders: using-the-tre/handling-files-and-folders.md
      - Software, modules, requesting installs: using-the-tre/software,-modules,-requesting-installs.md
      - Module Manager User Guide: using-the-tre/module-manager-guide.md
      - Running a GWAS: using-the-tre/running-a-gwas.md
  - What genetic and health data are where?:
      - TRE identifiers: what-genetic-and-health-data-are-where/tre-identifiers.md
      - How are data linked?: what-genetic-and-health-data-are-where/how-are-data-linked.md
      - Sources of "raw" health data: what-genetic-and-health-data-are-where/sources-of-raw-health-data.md
      - Phenotype curation: what-genetic-and-health-data-are-where/phenotype-curation.md
      - Bespoke phenotypes: what-genetic-and-health-data-are-where/bespoke-phenotypes.md
  - Getting data in and out of the TRE: 
      - How to get your data in: getting-data-in-and-out-of-the-TRE/how-to-get-your-data-in.md
      - Requesting data out of the TRE: getting-data-in-and-out-of-the-TRE/requesting-data-out-of-the-TRE.md
  - How tos:
      - How to update this documentation: how-tos/how-to-update-this-documentation.md
      - How to use docker: how-tos/how-to-use-docker.md
      - How to write hash symbols: how-tos/how-to-write-hash-symbols.md
  - Getting help: getting-help.md
#  - MkDocs Hosting Options: mkdocs-hosting-options.md
  
